version: "3"

services:
  web:
    container_name: nginx-php1
    image: nginx:1.18-alpine
    ports:
      - 8080:80
    volumes:
      - ./code:/usr/share/nginx/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    container_name: nginx-php2
    image: php:7.2.10-fpm-alpine
    volumes:
      - ./code:/var/www/html
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
